### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by aniaForever** [ltym2016/FilterTabView#1]
Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.support.v7.widget.RecyclerView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.samluys.filtertab.popupwindow.AreaSelectPopupWindow.initView(AreaSelectPopupWindow.java:54)
        at com.samluys.filtertab.base.BasePopupWindow.<init>(BasePopupWindow.java:84)
        at com.samluys.filtertab.popupwindow.AreaSelectPopupWindow.<init>(AreaSelectPopupWindow.java:48)
        at com.samluys.filtertab.PopupEntityLoaderImp.getPopupEntity(PopupEntityLoaderImp.java:26)
        at com.samluys.filtertab.FilterTabView.addFilterItem(FilterTabView.java:184)
        at com.samluys.pullfilterviewdemo.MainActivity.onCreate(MainActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.RecyclerView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.samluys.filtertab.popupwindow.AreaSelectPopupWindow.initView(AreaSelectPopupWindow.java:54) 
        at com.samluys.filtertab.base.BasePopupWindow.<init>(BasePopupWindow.java:84) 
        at com.samluys.filtertab.popupwindow.AreaSelectPopupWindow.<init>(AreaSelectPopupWindow.java:48) 
        at com.samluys.filtertab.PopupEntityLoaderImp.getPopupEntity(PopupEntityLoaderImp.java:26) 
        at com.samluys.filtertab.FilterTabView.addFilterItem(FilterTabView.java:184) 
        at com.samluys.pullfilterviewdemo.MainActivity.onCreate(MainActivity.java:43) 
        at android.app.Activity.performCreate(Activity.java:6237) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/com.samluys.pullfilterviewdemo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.samluys.pullfilterviewdemo-2/lib/x86, /vendor/lib, /system/lib]]

**Comment by aniaForever** [comment]
已解决，依赖中添加了Recyclerview
